print("Hello!")
print ("What is the name of the city you grew up in?")
user_city = input ()
print ("What is the name of your pet?")
user_pet_name = input()
print ("Computer generated band name:")
print(user_city +" "+ user_pet_name)
